find_package(PkgConfig)

PKG_CHECK_MODULES(PC_GR_PSCR_LMR2LTE gnuradio-PSCR_LMR2LTE)

FIND_PATH(
    GR_PSCR_LMR2LTE_INCLUDE_DIRS
    NAMES gnuradio/PSCR_LMR2LTE/api.h
    HINTS $ENV{PSCR_LMR2LTE_DIR}/include
        ${PC_PSCR_LMR2LTE_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    GR_PSCR_LMR2LTE_LIBRARIES
    NAMES gnuradio-PSCR_LMR2LTE
    HINTS $ENV{PSCR_LMR2LTE_DIR}/lib
        ${PC_PSCR_LMR2LTE_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
          )

include("${CMAKE_CURRENT_LIST_DIR}/gnuradio-PSCR_LMR2LTETarget.cmake")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GR_PSCR_LMR2LTE DEFAULT_MSG GR_PSCR_LMR2LTE_LIBRARIES GR_PSCR_LMR2LTE_INCLUDE_DIRS)
MARK_AS_ADVANCED(GR_PSCR_LMR2LTE_LIBRARIES GR_PSCR_LMR2LTE_INCLUDE_DIRS)
