/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sip_signaling.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f2286620da0d9ad03f4ffa93822b1ec6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <PSCR_LMR2LTE/sip_signaling.h>
// pydoc.h is automatically generated in the build directory
#include <sip_signaling_pydoc.h>

void bind_sip_signaling(py::module& m)
{

    using sip_signaling    = ::gr::PSCR_LMR2LTE::sip_signaling;


    py::class_<sip_signaling, gr::block, gr::basic_block,
        std::shared_ptr<sip_signaling>>(m, "sip_signaling", D(sip_signaling))

        .def(py::init(&sip_signaling::make),
           py::arg("SIP_domain"),
           py::arg("PCSCF_addr"),
           D(sip_signaling,make)
        )
        



        ;




}








