/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-PSCR_LMR2LTE
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_PSCR_LMR2LTE_API_H
#define INCLUDED_PSCR_LMR2LTE_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_PSCR_LMR2LTE_EXPORTS
#define PSCR_LMR2LTE_API __GR_ATTR_EXPORT
#else
#define PSCR_LMR2LTE_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_PSCR_LMR2LTE_API_H */
